name: ciko_chat
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  zego_uikit_prebuilt_live_audio_room: ^2.0.1
  firebase_core: ^2.6.0
  firebase_auth: ^4.2.7
  cloud_firestore: ^4.4.1
  google_sign_in: ^5.4.4
  intl: ^0.17.0
  material_design_icons_flutter: ^6.0.7096
  dio: ^5.0.0
  flutter_animate: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
